# Generated by Django 3.1.1 on 2020-09-23 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('NL', 'Не ищю работу'), ('RTO', 'Готов к предложениям'), ('LJ', 'Ищу работу')], default='LJ', max_length=10)),
                ('salary', models.FloatField()),
                ('grade', models.CharField(choices=[('INTERN', 'Стажер'), ('JUNIOR', 'Младший разработчик'), ('MIDDLE', 'Разработчик'), ('SENIOR', 'Старший разработчик'), ('LEAD', 'Руководитель разработки')], default='JUNIOR', max_length=50)),
                ('education', models.TextField(max_length=500)),
                ('experience', models.TextField(max_length=500)),
                ('portfolio', models.CharField(max_length=100)),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacancies.specialty')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
