# Generated by Django 3.1.1 on 2020-09-24 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='name',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='surname',
        ),
    ]
